package model;

import java.time.LocalDateTime;

/**
 * Standard TA application form for one TA and one course.
 *
 * <p>Forms may be generated by AI or fallback logic, edited by the TA, and then
 * submitted for MO review. Each form is identified by the pair of TA email and
 * course id.</p>
 *
 * @author BUPT Group33
 * @version 1.0
 * @since 1.0
 */
public class ApplicationForm {
    /** The email address of the TA who submitted this form. */
    private String taEmail;
    /** The unique identifier of the course this form applies to. */
    private String courseId;
    /** The applicant's display name. */
    private String applicantName;
    /** The applicant's email address. */
    private String email;
    /** The applicant's educational background. */
    private String education;
    /** The applicant's relevant skills. */
    private String skills;
    /** The applicant's relevant work or academic experience. */
    private String relevantExperience;
    /** The applicant's project experience. */
    private String projectExperience;
    /** Explanation of why the applicant is a good fit for the course. */
    private String courseFit;
    /** Feedback provided by the MO reviewer on this application. */
    private String feedback;
    /** Whether this form has been submitted and is ready for review. */
    private boolean submitted;
    /** The timestamp of the last update to this form. */
    private LocalDateTime updatedAt;

    /**
     * Constructs an ApplicationForm for the specified TA and course.
     *
     * @param taEmail  the email address of the TA
     * @param courseId the unique identifier of the course
     */
    public ApplicationForm(String taEmail, String courseId) {
        this.taEmail = taEmail;
        this.courseId = courseId;
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Returns the email address of the TA who owns this form.
     *
     * @return the TA email address
     */
    public String getTaEmail() {
        return taEmail;
    }

    /**
     * Sets the email address of the TA who owns this form.
     *
     * @param taEmail the TA email address to set
     */
    public void setTaEmail(String taEmail) {
        this.taEmail = taEmail;
    }

    /**
     * Returns the unique identifier of the course this form applies to.
     *
     * @return the course identifier
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * Sets the unique identifier of the course this form applies to.
     *
     * @param courseId the course identifier to set
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }

    /**
     * Returns the applicant's display name.
     *
     * @return the applicant name, or {@code null} if not set
     */
    public String getApplicantName() {
        return applicantName;
    }

    /**
     * Sets the applicant's display name.
     *
     * @param applicantName the applicant name to set
     */
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    /**
     * Returns the applicant's email address.
     *
     * @return the email address, or {@code null} if not set
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the applicant's email address.
     *
     * @param email the email address to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the applicant's educational background.
     *
     * @return the education description, or {@code null} if not set
     */
    public String getEducation() {
        return education;
    }

    /**
     * Sets the applicant's educational background.
     *
     * @param education the education description to set
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * Returns the applicant's relevant skills.
     *
     * @return the skills description, or {@code null} if not set
     */
    public String getSkills() {
        return skills;
    }

    /**
     * Sets the applicant's relevant skills.
     *
     * @param skills the skills description to set
     */
    public void setSkills(String skills) {
        this.skills = skills;
    }

    /**
     * Returns the applicant's relevant work or academic experience.
     *
     * @return the relevant experience, or {@code null} if not set
     */
    public String getRelevantExperience() {
        return relevantExperience;
    }

    /**
     * Sets the applicant's relevant work or academic experience.
     *
     * @param relevantExperience the relevant experience to set
     */
    public void setRelevantExperience(String relevantExperience) {
        this.relevantExperience = relevantExperience;
    }

    /**
     * Returns the applicant's project experience.
     *
     * @return the project experience, or {@code null} if not set
     */
    public String getProjectExperience() {
        return projectExperience;
    }

    /**
     * Sets the applicant's project experience.
     *
     * @param projectExperience the project experience to set
     */
    public void setProjectExperience(String projectExperience) {
        this.projectExperience = projectExperience;
    }

    /**
     * Returns the applicant's explanation of course fit.
     *
     * @return the course fit explanation, or {@code null} if not set
     */
    public String getCourseFit() {
        return courseFit;
    }

    /**
     * Sets the applicant's explanation of course fit.
     *
     * @param courseFit the course fit explanation to set
     */
    public void setCourseFit(String courseFit) {
        this.courseFit = courseFit;
    }

    /**
     * Returns the feedback provided by the MO reviewer.
     *
     * @return the feedback text, or {@code null} if not set
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * Sets the feedback provided by the MO reviewer.
     *
     * @param feedback the feedback text to set
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    /**
     * Checks whether this form has been submitted for review.
     *
     * @return {@code true} if the form has been submitted, {@code false} otherwise
     */
    public boolean isSubmitted() {
        return submitted;
    }

    /**
     * Sets whether this form has been submitted for review.
     *
     * @param submitted {@code true} to mark the form as submitted
     */
    public void setSubmitted(boolean submitted) {
        this.submitted = submitted;
    }

    /**
     * Returns the timestamp of the last update to this form.
     *
     * @return the last updated timestamp
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the timestamp of the last update to this form.
     *
     * @param updatedAt the timestamp to set
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
